In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
# Loading the COVID-19 dataset into df(DataFrame)
df=pd.read_csv('covid19.csv')
df.head(2)

C:\Users\Sandip phuyal\AppData\Local\Temp\ipykernel_13812\2326257196.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('covid19.csv')

,Unnamed: 0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,2022-03-17,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,2022-03-17,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0

# Project Structure 
- Data Cleaning & Preparation
- Feature Enginnering
- Exploratiry Data Analysis (EDA)
- Country Comparison (Per Capita)
- Time-Series Trend Analysis
- Final Insights & Conclusions

# Data Cleaning

### Problems found in the dataSet
- Not needed columns[Unnamed: 0, index, time]
- Changing ['date'] column from 'text' to 'datetime' dtype.
- Changing ['deaths_new'] column from 'text' to 'numeric'
- make population, country and continent is inconsistent, if country is given them make populaiton the same otherwise drop.[ no NaN or change]
- A column Shift Error has occured in continent column causing some continents name to be shifted to be population and populaiton to be NaN.[i.e 876, 1789,3395,5032]
- There are 229 countries in the dataset, since the official number is 195 changes need to be made
- in the continent, Austrilia continent is switched to Oceania since misunderstanding can be made because of Austrilia state and Austrilia continent in matplot.

In [3]:
# [[ df.info() ]]Show us details about the DataFrame for eg:- we have 232232 rows, 18 columns

In [4]:
#  and -
# -Datatypes: we have day and time as text not time-series data[error]. 
#  we have deaths_new as a obj[text], make it numeric so u can do calculations on that columns.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232232 entries, 0 to 232231
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0       232232 non-null  int64
 1   index            232232 non-null  int64
 2   continent        231157 non-null  object
 3   country          232232 non-null  object
 4   population       208220 non-null  float64
 5   day              232232 non-null  object
 6   time             232232 non-null  object
 7   cases_new        201745 non-null  float64
 8   cases_active     229459 non-null  float64
 9   cases_critical   187609 non-null  float64
 10  cases_recovered  228499 non-null  float64
 11  cases_1M_pop     232210 non-null  float64
 12  cases_total      232232 non-null  int64
 13  deaths_new       150555 non-null  object
 14  deaths_1M_pop    204718 non-null  float64
 15  deaths_total     226553 non-null  float64
 16  tests_1M_pop     204256 non-null  float64
 17  tests_total      221572 non-null  float64
dtypes: float64(10), int64(3), object(5)
memory usage: 31.9+ MB

In [6]:
# looks like Unnamed, index and time is redudant columns, i can remove them later...
df.head()

,Unnamed: 0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,2022-03-17,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,2022-03-17,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,2022-03-16,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,2022-03-15,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,2022-03-14,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0

In [7]:
### This is directly load all the rows here. [the kernel might crash since the rows are like 200,000 ]
# with pd.option_context('display.max_rows',None, 'display.max_columns',None):display(df)

In [8]:
# I want to narrow down the columns so i can focus on the dataFrame.
df_subset=df[['country','day','cases_new','cases_1M_pop','deaths_1M_pop','population','cases_critical']]
df_subset

,country,day,cases_new,cases_1M_pop,deaths_1M_pop,population,cases_critical
0,Afghanistan,2022-03-17,128.0,4377.0,189.0,40418964.0,1124.0
1,Afghanistan,2022-03-17,126.0,4373.0,189.0,40416563.0,1124.0
2,Afghanistan,2022-03-16,108.0,4369.0,189.0,40414161.0,1124.0
3,Afghanistan,2022-03-15,180.0,4365.0,189.0,40411760.0,1124.0
4,Afghanistan,2022-03-14,118.0,4360.0,189.0,40409359.0,1124.0
...,...,...,...,...,...,...,...
232227,Zimbabwe,2020-04-02,1.0,0.5,NaN,NaN,NaN
232228,Zimbabwe,2020-03-31,2.0,0.5,NaN,NaN,NaN
232229,Zimbabwe,2020-03-28,2.0,0.3,NaN,NaN,NaN
232230,Zimbabwe,2020-03-27,NaN,0.2,NaN,NaN,NaN
232231,Zimbabwe,2020-03-23,NaN,0.2,NaN,NaN,NaN

In [9]:
df.head()

,Unnamed: 0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,2022-03-17,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,2022-03-17,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,2022-03-16,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,2022-03-15,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,2022-03-14,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0

In [10]:
#  Redudant columns, i removed 'time' because the data in this dataframe might not be consistent cuz 
#  COVID-19 data changes from days and weeks not hours[! the insights from the 'time[hours]' might not be reliable] 
df=df.drop(columns=['Unnamed: 0', 'index','time'])
df.head()

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,Asia,Afghanistan,40418964.0,2022-03-17,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,Asia,Afghanistan,40416563.0,2022-03-17,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,Asia,Afghanistan,40414161.0,2022-03-16,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,Asia,Afghanistan,40411760.0,2022-03-15,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,Asia,Afghanistan,40409359.0,2022-03-14,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0

In [11]:
# making 'day' column from text->datetime data and deaths_new from text to numeric
df['day']=pd.to_datetime(df['day'], errors='coerce')
df['deaths_new']=pd.to_numeric(df['deaths_new'], errors='coerce')

In [12]:
#continent is a str value it shouldn't have nullvalues, can use ffill and bfill. 
df.isnull().sum()

continent           1075
country                0
population         24012
day                    0
cases_new          30487
cases_active        2773
cases_critical     44623
cases_recovered     3733
cases_1M_pop          22
cases_total            0
deaths_new         81681
deaths_1M_pop      27514
deaths_total        5679
tests_1M_pop       27976
tests_total        10660
dtype: int64

In [13]:
# Error found [Column Shift Error] which caused some population to be NaN and continent to be population.
df['continent'].value_counts()

continent
Europe           59278
Asia             58350
North-America    52196
Africa           38559
South-America    17460
                 ...
17607301             1
89174452             1
10833701             1
986088               1
29735785             1
Name: count, Length: 136, dtype: int64

In [14]:
#checking again
df.groupby('continent')['country'].unique()

continent
10091169                                                      [Sweden]
10127290                                                  [Azerbaijan]
10189909                                                      [Jordan]
10200387                                                    [Portugal]
106708                                                         [Aruba]
                                           ...
Australia/Oceania    [Australia, Fiji, French-Polynesia, New-Caledo...
Europe               [Albania, Andorra, Austria, Belarus, Belgium, ...
North-America        [Anguilla, Antigua-and-Barbuda, Aruba, Bahamas...
Oceania              [Australia, Cook-Islands, Fiji, French-Polynes...
South-America        [Argentina, Bolivia, Brazil, Chile, Colombia, ...
Name: country, Length: 136, dtype: object

In [15]:
# Finding out which continents are corrupted 
# we can find this by making the continent numeric, since the column where error is in numeric we can ignore
# the string ones.
num_continent=pd.to_numeric(df['continent'],errors='coerce')
# Now lets filter. If numeric continent is NOT null, it means it is a bad row.
bad_data_mask = num_continent.notnull()
df_corruptedContinents=df[bad_data_mask]
df_corruptedContinents.head()

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
876,38807744,Afghanistan,NaN,2020-05-16,414.0,5155.0,7.0,745.0,156.0,6053,17.0,NaN,153.0,NaN,20854.0
1789,2878189,Albania,NaN,2020-05-16,18.0,180.0,1.0,705.0,318.0,916,NaN,NaN,31.0,NaN,11458.0
3395,77249,Andorra,NaN,2020-05-15,NaN,116.0,3.0,596.0,9851.0,761,NaN,NaN,49.0,NaN,1673.0
5032,97824,Antigua-and-Barbuda,NaN,2020-05-26,NaN,3.0,1.0,19.0,256.0,25,NaN,NaN,3.0,NaN,183.0
6419,45141794,Argentina,NaN,2020-05-16,NaN,4284.0,170.0,2497.0,158.0,7134,NaN,NaN,353.0,NaN,96893.0

In [16]:
# Changing the name of Austrilia continent to Oceania since austrilia name is both the state and the continent.
df.loc[df['continent']=='Austrilia/Oceania','continent']='Oceania'

In [17]:
real_continents=['Asia','Europe','North-America','South-America','Africa','Oceania']
mapping_df=df[df['continent'].isin(real_continents)].drop_duplicates('country')
continent_map=mapping_df.set_index('country')['continent'].to_dict()

In [18]:
df['continent'] = df['country'].map(continent_map)

In [19]:
# sorting 'day' into ascending order.
# df=df.sort_values(by=['country', 'day'])
# df.head()

In [20]:
# we are trying to group[DataFrame] the countries to subtable, so the data analysis doesn't go out of the
#  environment. Since populaiton of the country doesn't change day to day. we can make the population stagnent.

df['population']=df.groupby('country')['population'].ffill().bfill()
df

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,Asia,Afghanistan,40418964.0,2022-03-17,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,Asia,Afghanistan,40416563.0,2022-03-17,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,Asia,Afghanistan,40414161.0,2022-03-16,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,Asia,Afghanistan,40411760.0,2022-03-15,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,Asia,Afghanistan,40409359.0,2022-03-14,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,Africa,Zimbabwe,14843588.0,2020-04-02,1.0,7.0,NaN,NaN,0.5,8,NaN,NaN,1.0,NaN,NaN
232228,Africa,Zimbabwe,14843588.0,2020-03-31,2.0,6.0,NaN,NaN,0.5,7,NaN,NaN,1.0,NaN,NaN
232229,Africa,Zimbabwe,14843588.0,2020-03-28,2.0,4.0,NaN,NaN,0.3,5,NaN,NaN,1.0,NaN,NaN
232230,Africa,Zimbabwe,14843588.0,2020-03-27,NaN,2.0,NaN,NaN,0.2,3,1.0,NaN,1.0,NaN,NaN
232231,Africa,Zimbabwe,14843588.0,2020-03-23,NaN,3.0,NaN,NaN,0.2,3,NaN,NaN,NaN,NaN,NaN

In [21]:
# This drops rows that don't have a valid continent/population (like 'World' or errors)
df_cleaned = df.dropna(subset=['continent', 'population'])

In [22]:
print(f"Dataset cleaned. New shape: {df_cleaned.shape}")
print(df_cleaned['continent'].value_counts())

Dataset cleaned. New shape: (232196, 15)
continent
Europe           59781
Asia             58509
North-America    52344
Africa           38812
South-America    17546
Oceania           5204
Name: count, dtype: int64

In [29]:
# just checking the countries. There is only 195 recogized countries officially.
df['country'].nunique()

229

In [30]:
# cheking 
print(df[df['continent'] == 'Asia']['country'].unique())

['Afghanistan' 'Armenia' 'Azerbaijan' 'Bahrain' 'Bangladesh' 'Bhutan'
 'Brunei' 'Cambodia' 'China' 'Cyprus' 'Georgia' 'Hong-Kong' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Israel' 'Japan' 'Jordan' 'Kazakhstan' 'Kuwait'
 'Kyrgyzstan' 'Laos' 'Lebanon' 'Macao' 'Malaysia' 'Maldives' 'Mongolia'
 'Myanmar' 'Nepal' 'Oman' 'Pakistan' 'Palestine' 'Philippines' 'Qatar'
 'S-Korea' 'Saudi-Arabia' 'Singapore' 'Sri-Lanka' 'Syria' 'Taiwan'
 'Tajikistan' 'Thailand' 'Timor-Leste' 'Turkey' 'UAE' 'Uzbekistan'
 'Vietnam' 'Yemen']

In [31]:
print(df[df['continent'] == 'Europe']['country'].unique())

['Albania' 'Andorra' 'Austria' 'Belarus' 'Belgium'
 'Bosnia-and-Herzegovina' 'Bulgaria' 'Channel-Islands' 'Croatia' 'Czechia'
 'Denmark' 'Estonia' 'Faeroe-Islands' 'Finland' 'France' 'Germany'
 'Gibraltar' 'Greece' 'Hungary' 'Iceland' 'Ireland' 'Isle-of-Man' 'Italy'
 'Latvia' 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Malta' 'Moldova'
 'Monaco' 'Montenegro' 'Netherlands' 'North-Macedonia' 'Norway' 'Poland'
 'Portugal' 'Romania' 'Russia' 'San-Marino' 'Serbia' 'Slovakia' 'Slovenia'
 'Spain' 'Sweden' 'Switzerland' 'UK' 'Ukraine' 'Vatican-City']

In [32]:
print(df[df['continent'] == 'North-America']['country'].unique())

['Anguilla' 'Antigua-and-Barbuda' 'Aruba' 'Bahamas' 'Barbados' 'Belize'
 'Bermuda' 'British-Virgin-Islands' 'Canada' 'Caribbean-Netherlands'
 'Cayman-Islands' 'Costa-Rica' 'Cuba' 'Dominica' 'Dominican-Republic'
 'El-Salvador' 'Greenland' 'Grenada' 'Guadeloupe' 'Guatemala' 'Haiti'
 'Honduras' 'Jamaica' 'Martinique' 'Mexico' 'Montserrat' 'Nicaragua'
 'Panama' 'Saint-Kitts-and-Nevis' 'Saint-Lucia' 'Saint-Martin'
 'Saint-Pierre-Miquelon' 'Sint-Maarten' 'St-Barth' 'St-Vincent-Grenadines'
 'Trinidad-and-Tobago' 'Turks-and-Caicos' 'USA']

In [33]:
print(df[df['continent'] == 'South-America']['country'].unique())

['Argentina' 'Bolivia' 'Brazil' 'Chile' 'Colombia' 'Ecuador'
 'Falkland-Islands' 'French-Guiana' 'Guyana' 'Paraguay' 'Peru' 'Suriname'
 'Uruguay' 'Venezuela']

In [34]:
print(df[df['continent'] == 'Africa']['country'].unique())

['Algeria' 'Angola' 'Benin' 'Botswana' 'Burkina-Faso' 'Burundi'
 'Cabo-Verde' 'Cameroon' 'CAR' 'Chad' 'Comoros' 'Congo' 'Djibouti' 'DRC'
 'Egypt' 'Equatorial-Guinea' 'Eritrea' 'Eswatini' 'Ethiopia' 'Gabon'
 'Gambia' 'Ghana' 'Guinea' 'Guinea-Bissau' 'Ivory-Coast' 'Kenya' 'Lesotho'
 'Liberia' 'Libya' 'Madagascar' 'Malawi' 'Mali' 'Mauritania' 'Mauritius'
 'Mayotte' 'Morocco' 'Mozambique' 'Namibia' 'Niger' 'Nigeria' 'Rwanda'
 'Saint-Helena' 'Sao-Tome-and-Principe' 'Senegal' 'Seychelles'
 'Sierra-Leone' 'Somalia' 'South-Africa' 'South-Sudan' 'Sudan' 'Tanzania'
 'Togo' 'Tunisia' 'Uganda' 'Western-Sahara' 'Zambia' 'Zimbabwe']

In [35]:
print(df[df['continent'] == 'Oceania']['country'].unique())

['Australia' 'Cook-Islands' 'Fiji' 'French-Polynesia' 'Kiribati'
 'Marshall-Islands' 'Micronesia' 'New-Caledonia' 'New-Zealand' 'Palau'
 'Papua-New-Guinea' 'Samoa' 'Solomon-Islands' 'Tonga' 'Vanuatu'
 'Wallis-and-Futuna']

In [37]:
# define the territories you want to remove
territories_to_remove = [
    'Hong-Kong','Channel-Islands', 'Faeroe-Islands', 
    'Gibraltar', 'Isle-of-Man', 'Anguilla', 'Aruba', 
    'British-Virgin-Islands', 'Caribbean-Netherlands', 'Cayman-Islands',
    'Guadeloupe', 'Martinique', 'Montserrat', 'Saint-Martin', 
    'Saint-Pierre-Miquelon', 'Sint-Maarten', 'St-Barth', 'Turks-and-Caicos', 
    'Mayotte', 'Saint-Helena', 'Western-Sahara', 'Falkland-Islands', 
    'French-Guiana', 'Cook-Islands', 'French-Polynesia', 'New-Caledonia', 
    'Wallis-and-Futuna'
]

# 2. Use the "NOT" operator (~) to keep only countries NOT in that list
df_countries_only = df[~df['country'].isin(territories_to_remove)]

# 4. Check the new count
print(f"Remaining unique 'countries': {df_countries_only['country'].nunique()}")

Remaining unique 'countries': 202

In [42]:
extra_error={
    'Diamond-Princess', 'Diamond-Princess-', 
    'MS-Zaandam', 'MS-Zaandam-',
    'Guam', 'Puerto-Rico', 'US-Virgin-Islands'
}
df_final_195 = df_countries_only[~df_countries_only['country'].isin(extra_error)]
print(f"Final Count of Countries: {df_final_195['country'].nunique()}")

Final Count of Countries: 195

In [43]:
current_list = set(df_final_195['country'].unique())

In [44]:
current_list

{'Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua-and-Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia-and-Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina-Faso',
 'Burundi',
 'CAR',
 'Cabo-Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa-Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'DRC',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican-Republic',
 'Ecuador',
 'Egypt',
 'El-Salvador',
 'Equatorial-Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Greenland',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory-Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall-Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New-Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North-Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua-New-Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'S-Korea',
 'Saint-Kitts-and-Nevis',
 'Saint-Lucia',
 'Samoa',
 'San-Marino',
 'Sao-Tome-and-Principe',
 'Saudi-Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra-Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon-Islands',
 'Somalia',
 'South-Africa',
 'South-Sudan',
 'Spain',
 'Sri-Lanka',
 'St-Vincent-Grenadines',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad-and-Tobago',
 'Tunisia',
 'Turkey',
 'UAE',
 'UK',
 'USA',
 'Uganda',
 'Ukraine',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican-City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe'}

# Creating new series for further explanation of the dataset
- for

In [23]:
# we need case fatality_rate to get insights between countries. 
# we will see NaN in the fatality rate because in the earlier days of COVID there were small entries with
# - case_total and deaths_total.
df['fatality_rate']=df['deaths_total']/df['cases_total']
df

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,fatality_rate
0,Asia,Afghanistan,40418964.0,2022-03-17,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0,0.043246
1,Asia,Afghanistan,40416563.0,2022-03-17,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0,0.043289
2,Asia,Afghanistan,40414161.0,2022-03-16,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0,0.043303
3,Asia,Afghanistan,40411760.0,2022-03-15,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0,0.043337
4,Asia,Afghanistan,40409359.0,2022-03-14,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0,0.043377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,Africa,Zimbabwe,14843588.0,2020-04-02,1.0,7.0,NaN,NaN,0.5,8,NaN,NaN,1.0,NaN,NaN,0.125000
232228,Africa,Zimbabwe,14843588.0,2020-03-31,2.0,6.0,NaN,NaN,0.5,7,NaN,NaN,1.0,NaN,NaN,0.142857
232229,Africa,Zimbabwe,14843588.0,2020-03-28,2.0,4.0,NaN,NaN,0.3,5,NaN,NaN,1.0,NaN,NaN,0.200000
232230,Africa,Zimbabwe,14843588.0,2020-03-27,NaN,2.0,NaN,NaN,0.2,3,1.0,NaN,1.0,NaN,NaN,0.333333
232231,Africa,Zimbabwe,14843588.0,2020-03-23,NaN,3.0,NaN,NaN,0.2,3,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df['death_per_active_case']=df['deaths_new']/ df['cases_active']

In [25]:
df.head()

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,fatality_rate,death_per_active_case
0,Asia,Afghanistan,40418964.0,2022-03-17,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0,0.043246,NaN
1,Asia,Afghanistan,40416563.0,2022-03-17,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0,0.043289,0.000203
2,Asia,Afghanistan,40414161.0,2022-03-16,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0,0.043303,0.000100
3,Asia,Afghanistan,40411760.0,2022-03-15,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0,0.043337,0.000195
4,Asia,Afghanistan,40409359.0,2022-03-14,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0,0.043377,0.000099

In [46]:
df['deaths_per_million_calc']=(df['deaths_total']/df['population'])*1000000
df.head()

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,fatality_rate,death_per_active_case,deaths_per_million_calc
0,Asia,Afghanistan,40418964.0,2022-03-17,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0,0.043246,NaN,189.292333
1,Asia,Afghanistan,40416563.0,2022-03-17,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0,0.043289,0.000203,189.303578
2,Asia,Afghanistan,40414161.0,2022-03-16,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0,0.043303,0.000100,189.191111
3,Asia,Afghanistan,40411760.0,2022-03-15,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0,0.043337,0.000195,189.177606
4,Asia,Afghanistan,40409359.0,2022-03-14,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0,0.043377,0.000099,189.139353

In [47]:
# we are making an average of 7 days case because there is information inconsistency with the cases
# due to various factor like weekends and information delay.
df['Avg_7day_cases']=(df.groupby('country')['cases_new']
    .rolling(7).mean().reset_index(level=0, drop=True))
df.head(2)

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,fatality_rate,death_per_active_case,deaths_per_million_calc,Avg_7day_cases
0,Asia,Afghanistan,40418964.0,2022-03-17,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0,0.043246,NaN,189.292333,NaN
1,Asia,Afghanistan,40416563.0,2022-03-17,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0,0.043289,0.000203,189.303578,NaN

# Exploratory Data Analysis

In [48]:
global_daily=df.groupby('day')['cases_new'].sum()

In [49]:
global_deaths=df.groupby('day')['deaths_new'].sum()

In [50]:
nepal=df[df['country']=='Nepal']
nepal[['day','fatality_rate','death_per_active_case','Avg_7day_cases','deaths_per_million_calc']].tail()

,day,fatality_rate,death_per_active_case,Avg_7day_cases,deaths_per_million_calc
139035,2020-03-25,NaN,NaN,1.142857,NaN
139036,2020-03-23,NaN,NaN,NaN,NaN
139037,2020-03-23,NaN,NaN,NaN,NaN
139038,2020-03-23,NaN,NaN,NaN,NaN
139039,2020-03-22,NaN,NaN,NaN,NaN

In [51]:
Afghanistan=df[df['country']=='Afghanistan']
Afghanistan[['day','fatality_rate','death_per_active_case','Avg_7day_cases']].tail()

           day  fatality_rate  death_per_active_case  Avg_7day_cases
955 2020-03-25       0.013514                    NaN             NaN
956 2020-03-24       0.023810                    NaN             NaN
957 2020-03-24       0.025000               0.026316             NaN
958 2020-03-22       0.029412               0.031250             NaN
959 2020-03-22            NaN                    NaN             NaN