In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
# Loading the COVID-19 dataset into df(DataFrame)
df=pd.read_csv('covid19.csv')
df.head(2)

C:\Users\Sandip phuyal\AppData\Local\Temp\ipykernel_23260\2326257196.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('covid19.csv')

,Unnamed: 0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,2022-03-17,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,2022-03-17,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0

# Project Structure 
- Data Cleaning & Preparation
- Feature Enginnering
- Exploratiry Data Analysis (EDA)
- Country Comparison (Per Capita)
- Time-Series Trend Analysis
- Final Insights & Conclusions

# Data Cleaning

In [3]:
# Show us details about the DataFrame for eg:- we have 232232 rows, 18 columns, and -
# -Datatypes: we have day and time as text not time-series data[error]. 
#  we have deaths_new as a obj[text], make it numeric so u can do calculations on that columns.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232232 entries, 0 to 232231
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0       232232 non-null  int64
 1   index            232232 non-null  int64
 2   continent        231157 non-null  object
 3   country          232232 non-null  object
 4   population       208220 non-null  float64
 5   day              232232 non-null  object
 6   time             232232 non-null  object
 7   cases_new        201745 non-null  float64
 8   cases_active     229459 non-null  float64
 9   cases_critical   187609 non-null  float64
 10  cases_recovered  228499 non-null  float64
 11  cases_1M_pop     232210 non-null  float64
 12  cases_total      232232 non-null  int64
 13  deaths_new       150555 non-null  object
 14  deaths_1M_pop    204718 non-null  float64
 15  deaths_total     226553 non-null  float64
 16  tests_1M_pop     204256 non-null  float64
 17  tests_total      221572 non-null  float64
dtypes: float64(10), int64(3), object(5)
memory usage: 31.9+ MB

In [4]:
# looks like Unnamed, index and time is redudant columns, i can remove them later...
df.head()

,Unnamed: 0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,2022-03-17,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,2022-03-17,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,2022-03-16,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,2022-03-15,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,2022-03-14,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0

In [5]:
### This is directly load all the rows here. [the kernel might crash since the rows are like 200,000 ]
# with pd.option_context('display.max_rows',None, 'display.max_columns',None):display(df)

In [6]:
# I want to narrow down the columns so i can focus on the dataFrame.
df_subset=df[['country','day','time','cases_new','cases_1M_pop','deaths_1M_pop','population','cases_critical']]
df_subset

,country,day,time,cases_new,cases_1M_pop,deaths_1M_pop,population,cases_critical
0,Afghanistan,2022-03-17,2022-03-17T20:15:03+00:00,128.0,4377.0,189.0,40418964.0,1124.0
1,Afghanistan,2022-03-17,2022-03-17T08:00:04+00:00,126.0,4373.0,189.0,40416563.0,1124.0
2,Afghanistan,2022-03-16,2022-03-16T08:00:04+00:00,108.0,4369.0,189.0,40414161.0,1124.0
3,Afghanistan,2022-03-15,2022-03-15T09:15:03+00:00,180.0,4365.0,189.0,40411760.0,1124.0
4,Afghanistan,2022-03-14,2022-03-14T09:15:03+00:00,118.0,4360.0,189.0,40409359.0,1124.0
...,...,...,...,...,...,...,...,...
232227,Zimbabwe,2020-04-02,2020-04-02T19:30:05+00:00,1.0,0.5,NaN,NaN,NaN
232228,Zimbabwe,2020-03-31,2020-03-31T06:45:05+00:00,2.0,0.5,NaN,NaN,NaN
232229,Zimbabwe,2020-03-28,2020-03-28T11:00:04+00:00,2.0,0.3,NaN,NaN,NaN
232230,Zimbabwe,2020-03-27,2020-03-27T08:00:05+00:00,NaN,0.2,NaN,NaN,NaN
232231,Zimbabwe,2020-03-23,2020-03-23T12:15:06+00:00,NaN,0.2,NaN,NaN,NaN

In [7]:
df.head()

,Unnamed: 0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,2022-03-17,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,2022-03-17,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,2022-03-16,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,2022-03-15,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,2022-03-14,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0

In [8]:
#  Redudant columns, i removed 'time' because the data in this dataframe might not be consistent cuz 
#  COVID-19 data changes from days and weeks not hours[! the insights from the 'time[hours]' might not be reliable] 
df=df.drop(columns=['Unnamed: 0', 'index','time'])
df.head()

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,Asia,Afghanistan,40418964.0,2022-03-17,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,Asia,Afghanistan,40416563.0,2022-03-17,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,Asia,Afghanistan,40414161.0,2022-03-16,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,Asia,Afghanistan,40411760.0,2022-03-15,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,Asia,Afghanistan,40409359.0,2022-03-14,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0

In [9]:
# making 'day' column from text->datetime data and deaths_new from text to numeric
df['day']=pd.to_datetime(df['day'], errors='coerce')
df['deaths_new']=pd.to_numeric(df['deaths_new'], errors='coerce')

In [10]:
# sorting 'day' into ascending order.
df=df.sort_values(by=['country', 'day'])
df.head()

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
958,Asia,Afghanistan,NaN,2020-03-22,10.0,32.0,NaN,1.0,0.9,34,1.0,NaN,1.0,NaN,NaN
959,Asia,Afghanistan,NaN,2020-03-22,10.0,33.0,NaN,1.0,0.9,34,NaN,NaN,NaN,NaN,NaN
956,Asia,Afghanistan,NaN,2020-03-24,2.0,40.0,NaN,1.0,1.0,42,NaN,NaN,1.0,NaN,NaN
957,Asia,Afghanistan,NaN,2020-03-24,16.0,38.0,NaN,1.0,1.0,40,1.0,NaN,1.0,NaN,NaN
953,Asia,Afghanistan,NaN,2020-03-25,5.0,75.0,NaN,2.0,2.0,79,1.0,NaN,2.0,NaN,NaN

In [13]:
# we are trying to group[DataFrame] the countries to subtable, so the data analysis doesn't go out of the
#  environment. Since populaiton of the country doesn't change day to day. we can make the population stagnent.

df['population']=df.groupby('country')['population'].ffill().bfill()
df

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,populaiton
958,Asia,Afghanistan,38850966.0,2020-03-22,10.0,32.0,NaN,1.0,0.9,34,1.0,NaN,1.0,NaN,NaN,38850966.0
959,Asia,Afghanistan,38850966.0,2020-03-22,10.0,33.0,NaN,1.0,0.9,34,NaN,NaN,NaN,NaN,NaN,38850966.0
956,Asia,Afghanistan,38850966.0,2020-03-24,2.0,40.0,NaN,1.0,1.0,42,NaN,NaN,1.0,NaN,NaN,38850966.0
957,Asia,Afghanistan,38850966.0,2020-03-24,16.0,38.0,NaN,1.0,1.0,40,1.0,NaN,1.0,NaN,NaN,38850966.0
953,Asia,Afghanistan,38850966.0,2020-03-25,5.0,75.0,NaN,2.0,2.0,79,1.0,NaN,2.0,NaN,NaN,38850966.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231343,Africa,Zimbabwe,15230365.0,2022-03-16,NaN,5068.0,12.0,232425.0,15949.0,242909,NaN,356.0,5416.0,140326.0,2137216.0,15230365.0
231344,Africa,Zimbabwe,15229773.0,2022-03-16,394.0,5068.0,12.0,232425.0,15950.0,242909,2.0,356.0,5416.0,140331.0,2137216.0,15229773.0
231340,Africa,Zimbabwe,15230956.0,2022-03-17,NaN,4968.0,12.0,233264.0,15997.0,243650,NaN,356.0,5418.0,140777.0,2144172.0,15230956.0
231341,Africa,Zimbabwe,15230956.0,2022-03-17,NaN,5161.0,12.0,232787.0,15978.0,243365,NaN,356.0,5417.0,140321.0,2137216.0,15230956.0
231342,Africa,Zimbabwe,15230365.0,2022-03-17,NaN,5161.0,12.0,232787.0,15979.0,243365,NaN,356.0,5417.0,140326.0,2137216.0,15230365.0

# Creating new series for further explanation of the dataset
- for

In [20]:
# we need case fatality_rate to get insights between countries. 
# we will see NaN in the fatality rate because in the earlier days of COVID there were small entries with
# - case_total and deaths_total.
df['fatality_rate']=df['deaths_total']/df['cases_total']
df

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,populaiton,fatality_rate
958,Asia,Afghanistan,38850966.0,2020-03-22,10.0,32.0,NaN,1.0,0.9,34,1.0,NaN,1.0,NaN,NaN,38850966.0,0.029412
959,Asia,Afghanistan,38850966.0,2020-03-22,10.0,33.0,NaN,1.0,0.9,34,NaN,NaN,NaN,NaN,NaN,38850966.0,NaN
956,Asia,Afghanistan,38850966.0,2020-03-24,2.0,40.0,NaN,1.0,1.0,42,NaN,NaN,1.0,NaN,NaN,38850966.0,0.023810
957,Asia,Afghanistan,38850966.0,2020-03-24,16.0,38.0,NaN,1.0,1.0,40,1.0,NaN,1.0,NaN,NaN,38850966.0,0.025000
953,Asia,Afghanistan,38850966.0,2020-03-25,5.0,75.0,NaN,2.0,2.0,79,1.0,NaN,2.0,NaN,NaN,38850966.0,0.025316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231343,Africa,Zimbabwe,15230365.0,2022-03-16,NaN,5068.0,12.0,232425.0,15949.0,242909,NaN,356.0,5416.0,140326.0,2137216.0,15230365.0,0.022296
231344,Africa,Zimbabwe,15229773.0,2022-03-16,394.0,5068.0,12.0,232425.0,15950.0,242909,2.0,356.0,5416.0,140331.0,2137216.0,15229773.0,0.022296
231340,Africa,Zimbabwe,15230956.0,2022-03-17,NaN,4968.0,12.0,233264.0,15997.0,243650,NaN,356.0,5418.0,140777.0,2144172.0,15230956.0,0.022237
231341,Africa,Zimbabwe,15230956.0,2022-03-17,NaN,5161.0,12.0,232787.0,15978.0,243365,NaN,356.0,5417.0,140321.0,2137216.0,15230956.0,0.022259
231342,Africa,Zimbabwe,15230365.0,2022-03-17,NaN,5161.0,12.0,232787.0,15979.0,243365,NaN,356.0,5417.0,140326.0,2137216.0,15230365.0,0.022259

In [21]:
df['death_per_active_case']=df['deaths_new']/ df['cases_active']

In [22]:
df.head()

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,populaiton,fatality_rate,death_per_active_case
958,Asia,Afghanistan,38850966.0,2020-03-22,10.0,32.0,NaN,1.0,0.9,34,1.0,NaN,1.0,NaN,NaN,38850966.0,0.029412,0.031250
959,Asia,Afghanistan,38850966.0,2020-03-22,10.0,33.0,NaN,1.0,0.9,34,NaN,NaN,NaN,NaN,NaN,38850966.0,NaN,NaN
956,Asia,Afghanistan,38850966.0,2020-03-24,2.0,40.0,NaN,1.0,1.0,42,NaN,NaN,1.0,NaN,NaN,38850966.0,0.023810,NaN
957,Asia,Afghanistan,38850966.0,2020-03-24,16.0,38.0,NaN,1.0,1.0,40,1.0,NaN,1.0,NaN,NaN,38850966.0,0.025000,0.026316
953,Asia,Afghanistan,38850966.0,2020-03-25,5.0,75.0,NaN,2.0,2.0,79,1.0,NaN,2.0,NaN,NaN,38850966.0,0.025316,0.013333

In [25]:
df['deaths_per_million_calc']=(df['deaths_total']/df['populaiton'])*1000000
df.head()

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,populaiton,fatality_rate,death_per_active_case,deaths_per_million_calc
958,Asia,Afghanistan,38850966.0,2020-03-22,10.0,32.0,NaN,1.0,0.9,34,1.0,NaN,1.0,NaN,NaN,38850966.0,0.029412,0.031250,0.025739
959,Asia,Afghanistan,38850966.0,2020-03-22,10.0,33.0,NaN,1.0,0.9,34,NaN,NaN,NaN,NaN,NaN,38850966.0,NaN,NaN,NaN
956,Asia,Afghanistan,38850966.0,2020-03-24,2.0,40.0,NaN,1.0,1.0,42,NaN,NaN,1.0,NaN,NaN,38850966.0,0.023810,NaN,0.025739
957,Asia,Afghanistan,38850966.0,2020-03-24,16.0,38.0,NaN,1.0,1.0,40,1.0,NaN,1.0,NaN,NaN,38850966.0,0.025000,0.026316,0.025739
953,Asia,Afghanistan,38850966.0,2020-03-25,5.0,75.0,NaN,2.0,2.0,79,1.0,NaN,2.0,NaN,NaN,38850966.0,0.025316,0.013333,0.051479

In [32]:
# we are making an average of 7 days case because there is information inconsistency with the cases
# due to various factor like weekends and information delay.
df['Avg_7day_cases']=(df.groupby('country')['cases_new']
    .rolling(7).mean().reset_index(level=0, drop=True))
df.head(2)

,continent,country,population,day,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total,populaiton,fatality_rate,death_per_active_case,deaths_per_million_calc,Avg_7day_cases
958,Asia,Afghanistan,38850966.0,2020-03-22,10.0,32.0,NaN,1.0,0.9,34,1.0,NaN,1.0,NaN,NaN,38850966.0,0.029412,0.03125,0.025739,NaN
959,Asia,Afghanistan,38850966.0,2020-03-22,10.0,33.0,NaN,1.0,0.9,34,NaN,NaN,NaN,NaN,NaN,38850966.0,NaN,NaN,NaN,NaN

# Exploratory Data Analysis

In [36]:
global_daily=df.groupby('day')['cases_new'].sum()

In [37]:
global_deaths=df.groupby('day')['deaths_new'].sum()

In [49]:
nepal=df[df['country']=='Nepal']
nepal[['day','fatality_rate','death_per_active_case','Avg_7day_cases','deaths_per_million_calc']].tail()

,day,fatality_rate,death_per_active_case,Avg_7day_cases,deaths_per_million_calc
137820,2022-03-16,0.012218,NaN,47.857143,397.980099
137821,2022-03-16,0.012218,NaN,51.714286,397.999094
137817,2022-03-17,0.012217,NaN,50.571429,397.961094
137818,2022-03-17,0.012218,NaN,48.000000,397.961094
137819,2022-03-17,0.012218,NaN,45.428571,397.980099

In [44]:
Afghanistan=df[df['country']=='Afghanistan']
Afghanistan[['day','fatality_rate','death_per_active_case','Avg_7day_cases']].tail()

         day  fatality_rate  death_per_active_case  Avg_7day_cases
4 2022-03-14       0.043377               0.000099      166.000000
3 2022-03-15       0.043337               0.000195      175.857143
2 2022-03-16       0.043303               0.000100      138.714286
0 2022-03-17       0.043246                    NaN      104.428571
1 2022-03-17       0.043289               0.000203      110.857143